### ISSUE TITLE
What modifications needed to support Blazor as Azure DevOps Extension

### ISSUE THREAD

**Issue by GeorgeS2019** [MaciekWin3/azure-devops-blazor-extension#2]

**Comment by MaciekWin3** [comment]
Check my answer [here](https://github.com/MicrosoftDocs/azure-devops-docs/issues/13953#issuecomment-1910949523).

**Comment by GeorgeS2019** [comment]
@MaciekWin3 

If there any update in your repos?

**Comment by MaciekWin3** [comment]
I haven't made any changes yet, but I'm committed to keeping this repository updated. Now that [this issue](https://github.com/dotnet/aspnetcore/issues/52294) was resolved, has been resolved, my plan is to upgrade this project to .NET 8 and then streamline the template for simplicity, enabling users to quickly start their projects with ease.

**Comment by MaciekWin3** [comment]
Hi @GeorgeS2019, the first changes have been made. The project has been updated to .NET 8, and I've made some minor improvements. I'm going to close this issue, but if you have any more questions or suggestions, feel free to open another one.

**Comment by GeorgeS2019** [comment]
will this gives more possibilities for your blazor extension?

https://learn.microsoft.com/en-us/javascript/api/azure-devops-extension-sdk/

**Comment by MaciekWin3** [comment]
> will this gives more possibilities for your blazor extension?
> 
> https://learn.microsoft.com/en-us/javascript/api/azure-devops-extension-sdk/

Hi @GeorgeS2019, We are already using it [here](https://github.com/MaciekWin3/azure-devops-blazor-extension/blob/master/src/AzDevOpsBlazorExtension/wwwroot/SDK.js). But you are right, we can explore if we should keep it in one file or to use it as node module.
